### ISSUE TITLE
建议 

### ISSUE THREAD

**Issue by AllenCoder** [wustor/GradleModule#1]
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')

    librarys.each { k, v -> compile v }
}
```
这么配置 ，感觉有点优化过度了，首先每次的添加版本库都需要 指定 k -v，其次　如果有多种编译模式　，debug，release , xxx，对应不同的 依赖，你这种配置的k -v就会成很繁琐

**Comment by wustor** [comment]
可以在config中统一配置，debug,release,XXX的Map，然后根据不同的模式，遍历不同的Map,config里面可以无限复杂，但是APP下面的build.gradle应该尽量简单
